name: Generate Contributor Pie Chart

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  generate:
    uses: AnjusriKandi/contrib-pie-generator/.github/workflows/main.yml@v0
    with:
      chart-size: '6,6'  # [Optional] Give your Input for chart size (width,height)
      palette: '#EBE8DB, #D76C82, #B03052, #3D0301'  # [Optional] Give your Custom color palette (comma-separated hex values)
      repo-url: 'https://api.github.com/repos/AnjusriKandi/Online-Examination-System/contributors'  
